import turtle  # turtle - название библиотеки
import math

# В начале мы должны задать параметры как  shape (форма) color and speed
# turtle.shape ("turtle") # В скобках также писать arrow,circle,triangle

turtle.shape("arrow")
turtle.color("black")
turtle.speed(3)

size = 30
size2 = int((size ** 2 / 2) ** 0.5)

# фасад
turtle.forward(size * 12)
turtle.right(90)
turtle.forward(size * 10)
turtle.right(90)
turtle.forward(size * 12)
turtle.right(90)
turtle.forward(size * 10)
# крыша
turtle.right(45)
turtle.forward(size2 * 12)
turtle.right(90)
turtle.forward(size2 * 12)
turtle.right(135)
turtle.forward(size)
turtle.right(45)
# turtle.forward(size2 * 10)
# turtle.left(90)
# turtle.forward(size2 * 10)
# turtle.right(45)
# turtle.forward(size)
# # труба
# turtle.right(135)
# turtle.forward(size2 * 3)
# turtle.left(45)
# turtle.forward(size * 4)
# turtle.right(90)
# turtle.forward(size * 3)
# turtle.right(90)
# turtle.forward(size)
# turtle.right(45)
# turtle.forward(size2 * 9)
# turtle.left(45)
# # молдинг
# turtle.forward(size * 4.5)
# turtle.left(90)
# turtle.forward(size * 12)
# turtle.right(90)
# # цоколь дверь
# turtle.forward(size * 4)
# turtle.right(90)
# turtle.forward(size * 7)
# turtle.right(90)
# turtle.forward(size * 3)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 3)
# turtle.right(90)
# turtle.forward(size * 7)
# turtle.right(90)
# # балкон
# turtle.forward(size * 3.5)
# turtle.right(90)
# turtle.forward(size * 12)
# turtle.left(180)
# turtle.forward(size * 8)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 4)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.left(90)
# turtle.forward(size * 4)
# # лестница
# turtle.right(90)
# turtle.forward(size * 5)
# turtle.right(90)
# turtle.forward(size * 3)
# turtle.right(90)
# turtle.forward(size * 0.5)
# turtle.left(90)
# turtle.forward(size * 6)
# turtle.left(90)
# turtle.forward(size * 0.5)
# turtle.left(180)
# turtle.forward(size * 0.5)
# turtle.right(90)
# turtle.forward(size * 0.5)
# turtle.left(90)
# turtle.forward(size * 0.5)
# turtle.right(90)
# turtle.forward(size * 5)
# turtle.right(90)
# turtle.forward(size * 0.5)
# turtle.right(180)
# turtle.forward(size * 0.5)
# turtle.left(90)
# turtle.forward(size * 0.5)
# turtle.right(90)
# turtle.forward(size * 0.5)
# turtle.left(90)
# turtle.forward(size * 4)
# turtle.left(90)
# turtle.forward(size * 0.5)
# # колонны
# turtle.left(180)
# turtle.forward(size * 4)
# turtle.right(90)
# turtle.forward(size * 0.4)
# turtle.right(90)
# turtle.forward(size * 3.5)
# turtle.left(90)
# turtle.forward(size * 3.2)
# turtle.left(90)
# turtle.forward(size * 3.5)
# turtle.right(90)
# turtle.forward(size * 0.4)
# turtle.right(90)
# turtle.forward(size * 3.5)
# # окна
# turtle.penup()
# turtle.left(90)
# turtle.forward(size)
# turtle.left(90)
# turtle.forward(size * 0.5)
# turtle.pendown()
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.penup()
# turtle.right(90)
# turtle.forward(size * 4.5)
#
# turtle.pendown()
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.penup()
# turtle.forward(size * 8)
#
# turtle.pendown()
# turtle.right(90)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.penup()
# turtle.left(90)
# turtle.forward(size * 4.5)
#
# turtle.pendown()
# turtle.right(180)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2.5)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.penup()
# turtle.right(90)
# turtle.forward(size * 5)
# turtle.right(90)
# turtle.forward(size * 4)
#
# turtle.pendown()
# turtle.left(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.right(90)
# turtle.forward(size * 2)
# turtle.penup()
# turtle.right(180)
# turtle.forward(size * 5)
#
# turtle.pendown()
# turtle.circle(size)
